Provide optional value to date_submitted field
This was causing a local build to error out because by supplemental metadata did not have submission date as an available field., resulting in:
KeyError: 'date_submitted'
Providing a default value fixes this key error