onerror: Send the build log with the Slack message
Switches to Slack's files.upload API method which requires us to use a
proper token, as we also do in ncov-ingest, instead of an incoming
webhook.